### ISSUE TITLE
Very small font size if not in 'word-scrolling mode'

### ISSUE THREAD

**Issue by Melonadev** [gnusenpai/colemakclub#10]
Default setting (word-scrolling mode enabled):

![image](https://user-images.githubusercontent.com/66422959/141890868-059b04c6-9b61-498f-86e5-a210802eaac3.png)

Current settings (word-scrolling mode enabled):

![image](https://user-images.githubusercontent.com/66422959/141890642-3d0e012b-482d-4016-a489-b7fb35aaba56.png)

Changed settings:
![image](https://user-images.githubusercontent.com/66422959/141890667-bf40659b-9064-4da7-b2ce-43c33fc86ed0.png)

Wall of text (word-scrolling mode disabled):

![image](https://user-images.githubusercontent.com/66422959/141890768-981bd624-f67a-47a7-aa1c-01506e67bff2.png)

Font size should be bigger in my opinion. Maybe add a slider to adjust the font size or something?

**Comment by gnusenpai** [comment]
This was hard for me to noticeably reproduce, but I believe the font size should match the normal mode now.
