### ISSUE TITLE
[FR] Voice mode?

### ISSUE THREAD

**Issue by glyh** [gnusenpai/colemakclub#12]
As title, it would be great if there's a voice hint to tell me next word to type, so one can type blindly without looking the screen.

**Comment by gnusenpai** [comment]
This is definitely out of the scope of this project, but what is the use case?

**Comment by LeonhardTissen** [comment]
> This is definitely out of the scope of this project, but what is the use case?

I'd suggest an option to have the next word be spoken via Web Speech API and would love to make a PR if you change your mind
