### ISSUE TITLE
Major site functions broken

### ISSUE THREAD

**Issue by aYorky** [gnusenpai/colemakclub#14]
It seems most of the site's features are completely broken. I noticed this issue yesterday, and thought it might be a temporary issue, so I waited until today to say anything. The levels are not selectable, nor are the settings (i.e. the panel does not open). The keyboard layout does not appear, and while the text box accepts input, the timer does not start, nor are there even word prompts to follow along with.

Edit: After a little bit more looking around in here, it looks like https://gnusenpai.github.io/colemakclub/ is working, but not https://gnusenpai.net/colemakclub/ which is what I had bookmarked. Was the deployment destination changed or something?

**Comment by gnusenpai** [comment]
I'm not able to reproduce this, both deployments are up to date and I've not changed any relevant backend configuration in several months.
Maybe clear your localstorage for the broken site? I tested the recent changes using new and existing localstorage on Firefox and new localstorage on Chromium. It's possible I missed some weird edge-case with Chromium.

**Comment by aYorky** [comment]
Hm, I suppose it's possible that something in my localstorage or cache was messed up, but both sites are working again for me. Sorry to waste your time.

**Comment by gnusenpai** [comment]
Server-side caching could be to blame, I believe I've restarted nginx a few times since this issue was posted, so that could be why it started working for you. In the future, I'll make sure to restart things when I make major changes.
