### ISSUE TITLE
Bug: Server not loading

### ISSUE THREAD

**Issue by ianfromdover** [gnusenpai/colemakclub#19]
![Screenshot 2022-07-14 at 10 12 58 AM](https://user-images.githubusercontent.com/62384984/178883261-db24a22f-6509-46b8-b472-7d68be08dbd7.png)

It's not a network error because all my other github pages work

OS: MacOS Catalina
Browser: v15.5
Steps to reproduce: click on the linked github page under environments.

**Comment by gnusenpai** [comment]
Yup, the remote server my main site is hosted on is currently down (out of my control). Please use the alternative host in the meantime: [Github Pages](https://gnusenpai.github.io/colemakclub/). Both are linked in the readme of this repo.

**Comment by gnusenpai** [comment]
The main host has been restored.
