### ISSUE TITLE
Missing LICENSE

### ISSUE THREAD

**Issue by TechnologyClassroom** [gnusenpai/colemakclub#37]
I see you have no LICENSE for this project. The default is copyright.

I would suggest releasing the code under the AGPL-3.0-or-later or GPL-3.0-or-later license so that others are encouraged to contribute changes back to your project.

**Comment by gnusenpai** [comment]
The reason this project doesn't have a license is that the original this was forked from didn't have one either. The only copyright info I have is the notice at the last line of [index.html](https://github.com/gnusenpai/colemakclub/blob/32f4d6c84730bcaaabfab2de9f9fbe651a5cfb4e/index.html#L146). Given that, I feel like the project is technically on shaky ground as it is and I don't know if I can or should re-license it.

**Comment by radhesh1** [comment]
cant this be solved by actually copyrighting the software under both your names

**Comment by gnusenpai** [comment]
I believe Nick is the original author of [DitchQwerty](https://www.ditchqwerty.com/). I seen a cached result on a search engine for what I think used to be his website (nicholasmariano.dev) and it mentioned DitchQwerty, but it seems to be inaccessible now.
So I think Sigges forked Nick's DitchQwerty much like we forked Sigges' Colemak Academy, which complicates this a bit further.

**Comment by TechnologyClassroom** [comment]
The nicholasmariano.dev is still up, but has an expired certificate. You can browse the page by starting a chromium-based browser with settings to ignore certificate errors.

    chromium --ignore-certificate-errors https://nicholasmariano.dev

The bottom of the page includes a phone number, email address, and a GitHub address. @Nemcorp

**Comment by gnusenpai** [comment]
@TechnologyClassroom I knew about the certificate issue, but I couldn't figure out how to coax any browser into letting me in, thanks for the tip.
I noticed that in the footer it says: `@Siggesmunde Design`, is Sigges the same guy? It seems a bit strange that he would make 2 very similar but different sites, and only 1 is mentioned.

**Comment by TechnologyClassroom** [comment]
I made a separate issue in that repo.

**Comment by Nemcorp** [comment]
Hi! Glad to see interest in this project. I will take a look at the license. Can I ask what you are planning on doing with it?

**Comment by TechnologyClassroom** [comment]
The README summarizes the changes in this repository.

### Features/Improvements
* Corrected Colemak-DH
* ANSI/ISO/Ortho keyboard selection
* Various usability/rendering fixes
* More accurate physical keyboard representation
* Persistent settings via Local Storage

### Plans
* Visual overhaul
* Color-coded fingermap
